### ISSUE TITLE
Update testing b-values with a more realistic set

### ISSUE THREAD

**Issue by etpeterson** [OSIPI/TF2.4_IVIM-MRI_CodeCollection#10]
They're currently skewed high, so should be updated with literature supported values.

**Comment by kailash360** [comment]
Hello @etpeterson 

I would like to work on this issue.

**Comment by etpeterson** [comment]
Oh, also: @kailash360 and @AhmedBasem20 you're GSoC students, please join our slack as well!

**Comment by AhmedBasem20** [comment]
Thanks @etpeterson for the detailed reply.

> I was thinking that in the meantime we could find several reasonable sets, perhaps targeting brain, liver, and muscle. And add them more as reference values that we could use within the repository. 

I'm trying to find how and where to update those sets. I see that the bvalues is filled this way:
https://github.com/OSIPI/TF2.4_IVIM-MRI_CodeCollection/blob/a9cc38846b304216c437c008a35df81d2f10125f/tests/IVIMmodels/data/test_GenerateData.py#L11

on several parts of the code, I guess if we replaced `np.linspace(0, 1000, 11)` with our defined bvalues set, the tests will be regenerated based on it, what do you think about this?

Anyways, I'm currently trying to run the project so that I can test that everythings works locally before pushing any code.

**Comment by etpeterson** [comment]
The [generic.json](https://github.com/OSIPI/TF2.4_IVIM-MRI_CodeCollection/blob/main/tests/IVIMmodels/unit_tests/generic.json) file was created with [this](https://github.com/OSIPI/TF2.4_IVIM-MRI_CodeCollection/blob/main/phantoms/MR_XCAT_qMRI/sim_ivim_sig.py) script. What we're missing now are the data files used to generate it. I inquired about the new data location, all I know currently is that it's somewhere on Zenodo. Until we get the data there's not much we can do here.

What you're finding are places where our lack of predefined bvalue sets are being filled in with linspaces. If you create a few sets in a file that we could perhaps call by name, that would be a good start.

For example, something like this to replace what you found. Note this is just an example and the actual implementation could vary.
```
from utilities.bvalues.presets import Brain

pytest.param(0, Brain.number(11), id='0')
```

I could imagine sets from papers could be added and referred to similarly as well.
`from utillities.bvalues.presets import <refname>`

Maybe starting with 5 presets for now - at least the framework would make more easy to add. Does something like that sound good for a first contribution?

**Comment by AhmedBasem20** [comment]
This sounds good to me! Will give it a try and let you know, Thanks.

**Comment by etpeterson** [comment]
@kailash360 Let me know if you're still interested and we can definitely find something for you.

**Comment by kailash360** [comment]
Sure @etpeterson, if there is some other issue I would love to work on it.

**Comment by etpeterson** [comment]
@kailash360 @Unique-Usman I created a few more issues in the repo. Take a look and see if anything looks interesting. Also, if you have other thoughts feel free to suggest them!

**Comment by oliverchampion** [comment]
@etpeterson thanks for checking this. Yes, I think it makes sense if one student works on this and the other works on another issue. Alternatively, we could have both work on this issue, but we will only merge 1 pull request. 

The data is at https://zenodo.org/records/10696605

If someone could check my merge request, the data should be downloaded automatically whenever it is needed in the code.
