### ISSUE TITLE
Update the github workflow

### ISSUE THREAD

**Issue by etpeterson** [OSIPI/TF2.4_IVIM-MRI_CodeCollection#42]
### Feature description

The github workflow is generating deprecation warnings and should be updated.

### Describe the solution

Both workflows are generating these warnings. `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.` They are still running, but should be updated.

### Are you working on this?

None

**Comment by Unique-Usman** [comment]
hello @etpeterson let me fix this then, I can take another issue.

**Comment by etpeterson** [comment]
Actually, and strangely this broke the Algorithm Analysis workflow. https://github.com/OSIPI/TF2.4_IVIM-MRI_CodeCollection/actions/runs/8114822453

Any ideas why?

**Comment by Unique-Usman** [comment]
None yet, let me try look into it.

**Comment by etpeterson** [comment]
Thanks. To get those to run on your branch you can temporarily add yourself or your branch in the filter for the workflow. It's near the top of the workflow file. That way you can iterate easily and remove it later for the final merge.

**Comment by Unique-Usman** [comment]
@etpeterson I was able to fix the issue, the upload_artifact and download_artifact v4 actions are not yet supported for GHES. So, I had to downgrade it back to v3.

**Comment by etpeterson** [comment]
Ok, thanks!
