### ISSUE TITLE
Push Algorithm Analysis result plots to a static github page

### ISSUE THREAD

**Issue by etpeterson** [OSIPI/TF2.4_IVIM-MRI_CodeCollection#46]
### Feature description

The Algorithm Analysis workflow automatically generates some nice plots. It may be possible to automatically push those to a static github page so they're easy to view.

### Describe the solution

The [Figures](https://github.com/OSIPI/TF2.4_IVIM-MRI_CodeCollection/actions/runs/8098690315/artifacts/1286493783) generated in the [Algorithm Analysis workflow](https://github.com/OSIPI/TF2.4_IVIM-MRI_CodeCollection/actions/runs/8098690315) could probably be uploaded to a simple static github page. This would be a nice way to visualize the most recent results.

### Additional context

I am not sure if it is possible to fully automate this. It would involve exploring the options and testing it. If it's not possible, that's a good finding as well.

### Are you working on this?

None

**Comment by AhmedBasem20** [comment]
@etpeterson Would love to work on this one as well!

**Comment by etpeterson** [comment]
Sure! I think this is fairly self explanatory. Probably just adding a push stage once the figures are generated would be enough. The harder part would be to figure out how to push it and update the page. I'm not sure it's even possible how I imagine it, but I'd like to learn more.

**Comment by AhmedBasem20** [comment]
@etpeterson my approach is to create a simple HTML file where we just display all the PDFs using it. This file will be inside the Figures folder. And then we can use this action: https://github.com/JamesIves/github-pages-deploy-action to add this folder to a new `gh-pages` branch and then publish it to be available on this url: https://OSIPI.github.io/TF2.4_IVIM-MRI_CodeCollection

```
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: Figures
```

**Comment by etpeterson** [comment]
Sounds good. @oliverchampion is that site the right place for a results page to live? I presume we'd want something about the task force on the front and maybe a link to results?

**Comment by oliverchampion** [comment]
@ericpete @AhmedBasem20, not entirely sure what the solution would entitle. 
But yes, the linked page should contain TF information. @petravanhoudt --> how do we achieve that?

I think we would something similar to the DCE solution: https://osipi.github.io/DCE-DSC-MRI_TestResults/intro.html
